# Configuraci\u00f3n de Supabase (PostgreSQL) - CORREGIDA
spring.datasource.url=jdbc:postgresql://db.ctbtzanjpxomfosxxsrm.supabase.co:5432/postgres?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=postgres
spring.datasource.password=Gestion2025

# Configuraci\u00f3n JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuraci\u00f3n HikariCP optimizada
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# Server configuration
server.port=8090

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# SUPABASE STORAGE
supabase.url=https://ctbtzanjpxomfosxxsrm.supabase.co
supabase.key=sb_secret_4cDztkLIrJsH1H40tRAwLg_Ru1EJNkP
supabase.bucket=imagenes-platos

#Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info.saborperuano2025@gmail.com
spring.mail.password=zgtvbevnkayinwif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Opcional (ver log si algo falla)
logging.level.org.springframework.mail=DEBUG